---
pagetitle: "COVID-19 cases in Trafford"
output: html_document
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse) ; library(httr) ; library(readxl) ;   library(lubridate) ; library(RcppRoll) ; library(reactable) ; library(zoo) ; library(ggtext) ; library(scales) ; library(shiny) ; library(ggrepel) ; library(sf) ; library(classInt) ; library(leaflet) ; library(htmlwidgets) ; library(htmltools)

# Mid-2019 population estimates
population <- read_csv("data/population.csv")

# Confirmed cases
# Source: Public Health England
# URL: https://coronavirus.data.gov.uk
raw <- read_csv("https://coronavirus.data.gov.uk/downloads/csv/coronavirus-cases_latest.csv")

cases <- raw %>% 
  filter(`Area type` %in% c("Nation", "Lower tier local authority"),
         `Area name` %in% c("Bolton", "Bury", "Manchester", "Oldham", "Rochdale", "Salford", "Stockport", "Tameside", "Trafford", "Wigan", "England")) %>% 
  mutate(date = as.Date(`Specimen date`, format = "%Y-%m-%d")) %>% 
  select(date,
         area_code = `Area code`,
         area_name = `Area name`,
         new_cases = `Daily lab-confirmed cases`) %>% 
  arrange(date) %>% 
  group_by(area_code, area_name) %>%
  complete(date = seq.Date(min(date), max(date), by = "day")) %>% 
  mutate(new_cases = replace_na(new_cases, 0)) %>% 
  ungroup() %>% 
  fill(area_name) %>%
  bind_rows(
    filter(., area_name != "England") %>% 
    group_by(., date) %>%
      summarise(area_code = "E11000001",
                area_name = "Greater Manchester",
                date = unique(date),
                new_cases = sum(new_cases))
    )

weekly_cases <- raw %>% 
  filter(`Area type` == "Lower tier local authority") %>% 
  mutate(date = as.Date(`Specimen date`, format = "%Y-%m-%d")) %>% 
  select(date,
         area_code = `Area code`,
         area_name = `Area name`,
         new_cases = `Daily lab-confirmed cases`) %>% 
  arrange(date) %>% 
  group_by(area_code, area_name) %>%
  complete(date = seq.Date(min(date), max(date), by = "day")) %>% 
  mutate(new_cases = replace_na(new_cases, 0)) %>% 
  ungroup() %>% 
  fill(area_name) %>%
  left_join(population, by = "area_code") %>% 
  mutate(rate = round(new_cases/population*100000,1)) %>%  
  group_by(area_name) %>% 
  mutate(previous_week = roll_sum(lag(rate, 7), 7, fill = NA, align = "right"),
         current_week = roll_sum(rate, 7, fill = NA, align = "right"),
         change = current_week/previous_week) %>% 
  ungroup() %>% 
  # include latest 'complete' cases
  filter(date == max(date)-days(5))

# ------------------------------------------------------------------------------

# MSOAs within Greater Manchester
# Source: ONS Open Geography Portal
# URL: https://geoportal.statistics.gov.uk

msoa <- st_read("data/msoa.geojson")

# Weekly confirmed cases by MSOA
# Source: Public Health England
# URL: https://coronavirus-staging.data.gov.uk/cases

tmp <- tempfile(fileext = ".xlsx")
GET(url = "https://coronavirus.data.gov.uk/downloads/msoa_data/MSOAs_latest.xlsx",
    write_disk(tmp))

msoa_cases <- read_xlsx(tmp, sheet = 2, skip = 8) %>% 
  filter(`MSOA code` %in% msoa$msoa11cd) %>% 
  select(lad19nm = `Local authority district name`,
         msoa11cd = `MSOA code`,
         msoa11hclnm = `House of Commons Library MSOA Name`,
         tail(names(.), 1)) %>% 
  pivot_longer(-c(lad19nm, msoa11cd, msoa11hclnm), 
               names_to = "week", 
               names_pattern = "wk_(.*)", 
               values_to = "n") %>% 
  mutate(week = parse_number(week),
         date = ymd("2019-12-29") + weeks(week),
         n = na_if(n, ".."),
         n = replace_na(n, 0),
         n = as.integer(n)) %>% 
  relocate(n, .after = last_col())
```

```{css}
@import url('https://fonts.googleapis.com/css2?family=Lato&display=swap');

.div {
  font-family: 'Lato', sans-serif;
}

.title {
  font-size: 18px;
  font-weight: bold;
}

.subtitle {
  margin: 8px 0;
  font-size: 14px;
}

.tbl {
  font-size: 14px;
  line-height: 18px;
}

.tbl a {
  color: inherit;
}

.header {
  border-bottom: 2px solid #555;
  font-size: 14px;
  font-weight: bold;
}

.header:hover {
  background-color: #eee;
}

.caption {
  text-align: right;
  font-size: 12px;
  color: #212121;
}
```

## Confirmed cases of coronavirus in Trafford

<br />
<div class="container-fluid">
<div class="row">
<div class = "col-sm-6">
<div class = "div">
```{r, dev = 'svg'}
rolling_cases <- cases %>% 
  filter(area_name == "Trafford") %>% 
  mutate(ma_cases = rollmean(new_cases, 14, align = "center", fill = NA)) 

    div(class = "subtitle",
        div(class = "title", "Daily confirmed cases"),
        paste("Trafford, to", format(max(rolling_cases$date), '%d %B %Y')))

ggplot() +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_col(data = rolling_cases, aes(x = date, y = new_cases), fill = "#39809E", alpha = 0.6) +
  geom_line(data = rolling_cases, aes(x = date, y = ma_cases, colour = "ma_cases"), size = 1) +
  scale_colour_manual(values = c("ma_cases" = "#39809E"), name = NULL, labels = "14-day rolling average") +
  scale_x_date(date_labels = "%b") +
  scale_y_continuous(expand = c(0.005, 0.005), position = "right") +
  labs(x = NULL, y = NULL, title = NULL, subtitle = NULL, caption = NULL) +
  theme_minimal(base_size = 20, base_family = "Lato") +
  theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.8, 1.005),
        legend.direction = "horizontal",
        legend.text = element_text(size = 12),
        axis.text.y = element_text(face = "bold")) 

    div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank")))
```
</div>
</div>
  
<div class = "col-sm-6">
<div class = "div">
```{r, dev = 'svg'}
total_cases <- cases %>% 
  filter(area_name == "Trafford") %>% 
  arrange(date) %>% 
  mutate(cum_cases = cumsum(new_cases))

    div(class = "subtitle",
        div(class = "title", "Cumulative cases"),
        paste("Trafford, to", format(max(total_cases$date), '%d %B %Y')))

ggplot(data = total_cases, aes(x = date, y = cum_cases, group = 1)) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_line(colour = "#39809E", size = 1.2) +
  scale_x_date(date_labels = "%b") +
  scale_y_continuous(expand = c(0.005, 0.005), labels = comma, position = "right") +
  labs(x = NULL, y = NULL, title = NULL, subtitle = NULL, caption = NULL) +
  theme_minimal(base_size = 20, base_family = "Lato") +
  theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_text(face = "bold"))

    div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank")))
```
</div>
</div>
</div>
<br />

<div class = "row">
<div class = "col-sm-6">
<div class = "div">
```{r, dev = 'svg'}
# Daily vs total confirmed cases
trajectory <- cases %>% 
  filter(area_name == "Trafford") %>% 
  arrange(date) %>% 
  mutate(cum_cases = cumsum(new_cases),
         ma_new_cases = rollmean(new_cases, 14, align = "center", fill = NA),
         ma_cum_cases = rollmean(cum_cases, 14, align = "center", fill = NA))

div(class = "subtitle",
        div(class = "title", "Daily versus total confirmed cases"),
         paste("Trafford, 14-day moving average, to", format(max(trajectory$date), '%d %B %Y')))

max_x <- ceiling(log10(max(trajectory$ma_cum_cases, na.rm = TRUE)))
max_y <- ceiling(log10(max(trajectory$ma_new_cases, na.rm = TRUE)))

trajectory %>% 
  filter(new_cases > 0) %>%
  ggplot(aes(x = ma_cum_cases, y = ma_new_cases)) +
  geom_line(colour = "#39809E", size = 1) +
  scale_x_log10(breaks = 10^(seq(0, max_x, length.out = max_x + 1)), labels = comma_format(accuracy = 1)) +
  scale_y_log10(breaks = 10^(seq(0, max_y, length.out = max_y + 1)), position = "right") +
  labs(x = "Total confirmed cases (log)", y = "Daily confirmed cases (log)", title = NULL, subtitle = NULL, caption = NULL) +
  theme_minimal(base_size = 20, base_family = "Lato") +
  theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12, hjust = 0, margin = margin(t = 10)),
        axis.title.y.right = element_text(size = 12, angle = 0, vjust = 1, margin = margin(l = -2)))

    div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank")))
```
</div>
</div>

<div class = "col-sm-6">
```{r, dev = 'svg'}
# rolling 14-day rate of cases
rolling_rate <- cases %>% 
  filter(area_name %in% c("Trafford", "Greater Manchester", "England")) %>%
  arrange(area_name, date) %>%
  left_join(population, by = "area_code") %>% 
  mutate(rate = round(new_cases/population*100000,1), 
         ma_rate = rollmean(rate, 14, align = "right", fill = NA),
         area_name = fct_relevel(area_name, "Trafford", "Greater Manchester", "England")) 

    div(class = "subtitle",
        div(class = "title", "Daily confirmed cases per 100,000 population"),
        paste("14-day moving average, to", format(max(rolling_rate$date), '%d %B %Y')))

ggplot(data = rolling_rate, aes(x = date, y = ma_rate, group = area_name)) +
  geom_hline(yintercept = 0, size = 0.3, colour = "#333333") +
  geom_line(aes(colour = area_name), size = 1) +
  # geom_text_repel(data = filter(rolling_rate, date == max(date)),
  #                 aes(label = round(ma_rate,1), colour = area_name), 
  #                 direction = "y", hjust = 0, nudge_x = 1, point.padding = NA, show.legend = FALSE) +
  scale_colour_manual(values = c("Trafford" = "#00AFBB", "Greater Manchester" = "#E7B800", "England" = "#757575")) +
  scale_x_date(date_labels = "%b") + # expand = c(0, 7), 
  scale_y_continuous(expand = c(0.005, 0.005), position = "right") +
  labs(x = NULL, y = NULL, title = "", subtitle = NULL, caption = NULL, colour = NULL) +
  theme_minimal(base_size = 20, base_family = "Lato") +
  theme(plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.68, 1.1),
        legend.direction = "horizontal",
        legend.text = element_text(size = 12),
        axis.text.y = element_text(face = "bold")) 

    div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank")))
```
</div>
</div>

<div class = "row">
<div class = "col-sm-12">
<div class = "div">
```{r map}
# weekly infection rate by MSOA
local_cases <- left_join(msoa, msoa_cases, by = "msoa11cd") %>% 
  mutate(rate = round(n/population*100000,1),
         popup = str_c("<strong>", msoa11hclnm, "</strong><br/><em>", lad19nm, "</em><br/><strong>", rate, "</strong> cases per 100,000<br/>", format(unique(.$date)-days(6), "%d %B"), " - ", format(unique(.$date), "%d %B")) %>% map(HTML))

# calculate class intervals for choropleth map
breaks <- classIntervals(local_cases[local_cases$rate > 0, ]$rate, n = 5, style = "jenks")$brks
pal <- colorBin(palette = "PuBu", domain = NULL, bins = breaks, na.color = "#D7D8D7")

div(class = "subtitle",
        div(class = "title", "Rate of confirmed cases by local area"),
        paste("Greater Manchester,", format(unique(local_cases$date)-days(6), "%d %B"), " - ", format(unique(local_cases$date), "%d %B")))

# create map
leaflet(data = filter(local_cases, rate != 0), width = "100%") %>%
  addTiles(urlTemplate = "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png", attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a> | <a href="https://www.ons.gov.uk/methodology/geography/licences">Contains OS data © Crown copyright and database right (2020)</a>') %>%
  setView(-2.35533522781156, 53.419025498197, zoom = 11) %>% 
  addPolygons(data = filter(local_cases, rate == 0), fillColor = "#FFFFFF", fillOpacity = 0.8, smoothFactor = 1, stroke = TRUE, weight = 0.5, color = "#bdbdbd", opacity = 1, label = ~popup, labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "13px", direction = "auto"), highlightOptions = highlightOptions(color = "#212121", weight = 2, bringToFront = TRUE)) %>% 
  addPolygons(fillColor = ~pal(rate), fillOpacity = 0.5, smoothFactor = 0.8, stroke = TRUE, weight = 1, color = "#bdbdbd", opacity = 1, label = ~popup, labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"), textsize = "13px", direction = "auto"), highlightOptions = highlightOptions(color = "#212121", weight = 2, bringToFront = TRUE)) %>%
  addLegend(pal = pal, values = ~rate, opacity = 0.7, title = "Cases per 100,000", position = "bottomright") %>%
  onRender(
    paste0("function(el, x) {$('head').append(","\'<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\'",");}"))

div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus-staging.data.gov.uk/cases', target = "_blank"), " | ", a("Office for National Statistics", href = 'https://www.nomisweb.co.uk/datasets/pestsyoaoa', target = "_blank")))
```
</div>
</div>
</div>

<div class = "row">
<div class = "col-sm-12">
<div class = "div">
```{r table}
# confirmed cases within last 14 days
recent_cases <- cases %>% 
  filter(date >= max(date) - days(14)) %>% 
  group_by(area_code, area_name) %>% 
  summarise(date = max(date),
            recent_cases = sum(new_cases)) %>%
  ungroup() %>% 
  left_join(population, by = "area_code") %>% 
  mutate(area_name = fct_relevel(factor(area_name), "Bolton", "Bury", "Manchester", "Oldham", "Rochdale",  "Salford", "Stockport", "Tameside", "Trafford", "Wigan", "Greater Manchester", "England"),
         recent_rate = round(recent_cases/population*100000,1),
         recent_cases = as.integer(recent_cases),
         population = as.integer(population)) %>% 
  select(date, area_name, recent_cases, population, recent_rate) %>% 
  arrange(area_name) %>% 
  select(-date)

palette <- function(x) rgb(colorRamp(c("#e6eff3", "#39809e"))(x), maxColorValue = 255)

tbl <- reactable(recent_cases,
          class = "tbl",
          compact = TRUE,
          fullWidth = TRUE,
          pagination = FALSE,
          wrap = FALSE,
          resizable = TRUE,
          defaultColDef = colDef(headerClass = "header", align = "left"),
          columns = list(
            area_name = colDef(name = "Name"),
            recent_cases = colDef(name = "Total cases",
                                  format = colFormat(separators = TRUE),
                                  align = "left"),
            population = colDef(name = "Population",
                                format = colFormat(separators = TRUE),
                                align = "left"),
            recent_rate = colDef(name = "Rate per 100,000",
                                 align = "left",
                                 style = function(value) {
                                   normalized <- (value - min(recent_cases$recent_rate)) / (max(recent_cases$recent_rate) - min(recent_cases$recent_rate))
                                   color <- palette(normalized)
                                   list(background = color)
                                   }))
)

div(class = "div",
    div(class = "subtitle",
        div(class = "title", "New confirmed cases in the last 14 days"),
        paste("to", format(max(cases$date), '%d %B %Y'))
        ),
    tbl,
    div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank")))
    )
```
</div>
</div>
</div>

<div class = "row">
<div class = "col-sm-12">
<div class = "div">
```{r,  fig.width = 12, dev = 'svg'}
# prevalence and growth
div(class = "subtitle",
    div(class = "title", "Local prevalence and growth rate in cases"),
    paste("Local authorities in England, as of", format(max(weekly_cases$date), '%d %B %Y')))

ggplot() +
  geom_hline(yintercept = 1, size = 1, colour = "#333333") +
  geom_point(data = filter(weekly_cases, !area_name %in% c("Bolton", "Bury", "Manchester", "Oldham", "Rochdale", "Trafford", "Salford", "Stockport", "Tameside", "Wigan")), aes(x = rate, y = change, size = population), shape = 21, fill = "#bdbdbd", colour = "#757575", alpha = 0.5) +
  geom_point(data = filter(weekly_cases, area_name == "Trafford"), 
             aes(rate, y = change, size = population), shape = 21, fill = "#00AFBB", colour = "#000000") +
  geom_text_repel(data = filter(weekly_cases, area_name == "Trafford"), 
                  aes(rate, y = change, label = area_name), size = 4, point.padding = 0.5) +
  # other GM local authorities
  geom_point(data = filter(weekly_cases, area_name %in% c("Bolton", "Bury", "Manchester", "Oldham", "Rochdale",  "Salford", "Stockport", "Tameside", "Wigan")), 
             aes(rate, y = change, size = population), shape = 21, fill = "#E7B800", colour = "#000000") +
  geom_text_repel(data = filter(weekly_cases, area_name %in% c("Bolton", "Bury", "Manchester", "Oldham", "Rochdale",  "Salford", "Stockport", "Tameside", "Wigan")),
                  aes(rate, y = change, label = area_name), size = 4, point.padding = 0.5) +
  annotate("text", x = max(weekly_cases$rate)*0.1, y = 5, label = "Low and rising", size = 7, hjust = 0, colour = "#757575") +
  annotate("text", x = max(weekly_cases$rate)*0.1, y = 0.4, label = "Low and falling", size = 7, hjust = 0, colour = "#757575") +
  annotate("text", x = max(weekly_cases$rate)*0.6, y = 5, label = "High and rising", size = 7, hjust = 0, colour = "#757575") +
  annotate("text", x = max(weekly_cases$rate)*0.6, y = 0.4, label = "High and falling", size = 7, hjust = 0, colour = "#757575") +
  scale_x_continuous(expand = c(0.005, 0.005),
                     breaks = seq(0, max(weekly_cases$rate), 5),
                     labels = seq(0, max(weekly_cases$rate), 5),
                     limits = c(0, max(weekly_cases$rate))) +
  scale_y_log10(expand = c(0.005, 0.005),
                breaks = c(0.25, 0.5, 1, 2, 4, 8),
                labels = paste(c(0.25, 0.5, 1, 2, 4, 8), "x"),
                limits = c(0.2, 10),
                position = "right") +
  labs(x = "New cases per 100k people", y = "Week-on-week change in cases",
       title = NULL, subtitle = NULL, caption = NULL) +
  theme_minimal(base_size = 20, base_family = "Lato") +
  theme(panel.grid.major = element_line(colour = "#bdbdbd"),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size = 18, face = "bold"),
        plot.subtitle = element_text(size = 15, margin = margin(b = 20)),
        plot.caption = element_text(size = 10, colour = "grey60"),
        axis.title.x = element_text(size = 12, hjust = 0, margin = margin(t = 10)),
        axis.title.y = element_text(size = 12, hjust = 0),
        legend.position = "none",
        axis.text = element_text(face = "bold")) +
  coord_cartesian(clip = "off")

div(class = "caption", p("Source: ", a("Public Health England", href = 'https://coronavirus.data.gov.uk/', target = "_blank"), "| Credits: ", a("@jburnmurdoch", href = 'https://twitter.com/jburnmurdoch/status/1288500620496908288', target = "_blank")))
```
</div>
</div>
</div>
</div>